version: "3.7"
services: 
#define nginx
 nginx:
  image: nginx
  ports:
  - ${nginx_port}:80 #Open port 8080 changed is ok
  depends_on:
  - php-mysql #Sync php-mysql service name
  volumes:
  - ./html:/usr/share/nginx/html
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/conf.d:/etc/nginx/conf.d
  networks:
   - webnet
#define php-fpm 
 php-mysql: 
  build:
   context: ./php
#   dockerfile: Dockerfile-alternate
   args:
    buildno: 1
  image: php-mysql:0.01 #new image name  changed is ok
  ports:
  - 9000:9000
  volumes:
  - ./html:/var/www/html
  container_name: phpfpm
  networks:
   - webnet
#define mysql
 mysql:
  image: mysql:${mysql_version} #mysql Version changed is ok
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD_VALUE} #mysql password changed is ok
  networks:
  - webnet
  ports:
  - 3306:3306
  volumes:
  - ./mysql/my.cnf:/etc/mysql/my.cnf
  - ./mysql/conf.d:/etc/mysql/conf.d
  - ./mysql/data:/var/lib/mysql
networks:
 webnet: