version: "3.7"
services: 
#define nginx
 nginx:
  image: nginx
  ports:
  - 8080:80
  depends_on:
  - php-mysql
  volumes:
  - ./html:/usr/share/nginx/html
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/conf.d:/etc/nginx/conf.d
  networks:
   - webnet
#define php-fpm 
 php-mysql: 
  build:
   context: ./php
#   dockerfile: Dockerfile-alternate
   args:
    buildno: 1
  image: php-mysql:0.01
  ports:
  - 9000:9000
  volumes:
  - ./html:/var/www/html
  container_name: phpfpm
  networks:
   - webnet
#define mysql
 mysql:
  image: mysql:5.7
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD:zxx@123456
  networks:
  - webnet
  ports:
  - 3306:3306
  volumes:
  - ./mysql/my.cnf:/etc/mysql/my.cnf
  - ./mysql/conf.d:/etc/mysql/conf.d
  - ./mysql/data:/var/lib/mysql
networks:
 webnet: 